### PR TITLE
New file api

### PR DESCRIPTION
**Pull request by vanpelt**
BAM, now you can call `run.files` or `run.file("name")` and download it with `.download()`

### CODE REVIEW

**Comment by hamelsmu** [comment]
This is amazing @vanpelt ... Thanks

cc: FYI @mmjb @mallamanis you can now download files from the project with the wandb dataset api, letting you know incase it is helpful

**Comment by hamelsmu** [comment]
@hohsiangwu, @tifret

**Comment by hamelsmu** [comment]
What's the ETA of pushing this to pypi?  Just want to use this for something I'm working on and wondering when it will be ready

**Comment by hohsiangwu** [comment]
:wave: I am trying to use `download` on the file object that I got but get 500 error. Also, if I copy the download link from the web UI and try to run `wget`, it also shows 500 error. While I can download directly from the web UI.

I guess there is some authentication we need to pass in? I did already set the `WANDB_API_KEY` env variable.

Here is the error message in case it helps.
```
In [59]: f.download()
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/wandb/apis/__init__.py in wrapper(*args, **kwargs)
     46         try:
---> 47             return func(*args, **kwargs)
     48         except requests.HTTPError as err:

/usr/local/lib/python3.6/dist-packages/wandb/apis/public.py in download(self, replace)
    483         response = requests.get(self._attrs["url"], stream=True)
--> 484         response.raise_for_status()
    485         path = self._attrs["name"]

/usr/lib/python3/dist-packages/requests/models.py in raise_for_status(self)
    839         if http_error_msg:
--> 840             raise HTTPError(http_error_msg, response=self)
    841

HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/github/search/7ydg3nrs/SelfAttentionModel_application_1541734216035_0145_model_best.pkl.gz

During handling of the above exception, another exception occurred:

CommError                                 Traceback (most recent call last)
<ipython-input-59-ea0566af65aa> in <module>
----> 1 f.download()

/usr/local/lib/python3.6/dist-packages/wandb/apis/__init__.py in wrapper(*args, **kwargs)
     47             return func(*args, **kwargs)
     48         except requests.HTTPError as err:
---> 49             raise CommError(err.response, err)
     50         except RetryError as err:
     51             if "response" in dir(err.last_exception) and err.last_exception.response is not None:

CommError: <Response [500]>
```

**Comment by vanpelt** [comment]
Hey @hohsiangwu we think this may have been caused by a brief GCP outage, are you seeing the same error if you try now?

**Comment by hohsiangwu** [comment]
Yeah, still seeing the same 500 error.

If you visit the url from the error message: `https://api.wandb.ai/github/search/7ydg3nrs/SelfAttentionModel_application_1541734216035_0145_model_best.pkl.gz` directly, you can see the error message as
```
Permission denied for read on project github/search as anonymous
```

**Comment by vanpelt** [comment]
Ahh, I see what was going on.  If you run `wandb login` on the machine you're running it from we write a file to your home directory named `.netrc` with your API key.  The current python package reads this automatically, but doesn't use the environment variable automatically.  

I'm pushing a fix until then, if you run `wandb login` on the machine it should work.

**Comment by hohsiangwu** [comment]
Awesome, sounds good, thanks a lot for looking into this!

**Comment by hohsiangwu** [comment]
Just to confirm, using `wandb login` for now works, thanks!

**Pull request merged**
