### PR TITLE
[WB-4107]: dont store secret info

### PR DESCRIPTION
**Pull request by KyleGoyette**
Link to Jira ticket:
https://wandb.atlassian.net/browse/WB-4107

### CODE REVIEW

**Review by vanpelt — COMMENTED** [review]
I don't think this should be a setting.  We just should just never store auth information, it's a major security issue.  Potentially one day we let people specify `auth` when running `git restore` but we should absolutely never store a users secrets if we can avoid it.

**Comment by KyleGoyette** [comment]
@raubitsj mentioned that he thought it should be a setting. I can remove that aspect of it.

**Comment by raubitsj** [comment]
> I don't think this should be a setting. We just should just never store auth information, it's a major security issue. Potentially one day we let people specify `auth` when running `git restore` but we should absolutely never store a users secrets if we can avoid it.

1) I think it should be a setting because we dont know what is a secret. 

The default should be to strip url passwords from git URLs.

2) I dont think `hide` is the right term either,  hide implies we are actually tracking it but we arent showing it.   Maybe:
wandb.Settings(git_strip_password=False)
where the default is True.

3) code is overaggressively mangling the url, it should just mess with the password field

So:
https://user:pass@host.xz:1234/path/to/repo.git/
Should turn into:
https://user@host.xz:1234/path/to/repo.git/

Currently this PR would turn that url into:
https://host.xz/path/to/repo.git/

And in this case:
git clone https://x-access-token:LONGTOKEN@github.com/Company/repo.git
would by default turn into:
git clone https://x-access-token@github.com/Company/repo.git

**Comment by vanpelt** [comment]
@raubitsj we should sync.  It's my thought that we should never store customer secrets.  If a user needs a git secret they need to manage it themselves and we could allow users to pass credentials to `wandb restore` or otherwise configure an agent with secrets.  Ever storing secrets in our config store seems like a bad idea.

**Review by raubitsj — APPROVED** [review]

**Pull request merged**
