### PR TITLE
Add wandb.run.config_static

### PR DESCRIPTION
**Pull request by raubitsj**
Sometimes people need to pass wandb.run.config to other processes.
Since wandb.run.config is a managed object this doesnt work very well.

wandb.run.config_static behaves like the wandb Config object in that you can refer to attributes or keys.

The difference is you cant change attributes/keys or add new keys/attributes

Note:
This is not adding onto the module.  For two reasons:
1. we should encourage people to use config and config_static off the run object
2. it is hard.  it can be done cleanly in python3.7+ and very hacky to create a property on a module

### CODE REVIEW

**Comment by raubitsj** [comment]
Closes #833

**Comment by vanpelt** [comment]
I simple test to assert a key in dynamic config exists in static would be good.

**Comment by raubitsj** [comment]
I will add a couple tests.
Was intentionally not going to support desc/value stuff since it more internal, not part of how users interact with wandb_config.Config

**Comment by vanpelt** [comment]
Yeah, I don’t want to support it.  Just wanted to be sure the data wasn’t
getting passed around with those keys in it.

**Pull request merged**
