### PR TITLE
Feature/sweep controller

### PR DESCRIPTION
**Pull request by raubitsj**
Local sweep controller with programmatic api.

still outstanding:
- need better testing for sweeps, there are cases not covered by existing sweep algo tests, and almost no coverage of the sweep infrastructure
- integration for ray/tune was removed to simplify this release.  third party algorithms will come in a different branch
- jupyter support for sweeps should be possible.

### CODE REVIEW

**Comment by richardliaw** [comment]
hey @raubitsj; I work on Tune, and I just stumbled upon this PR browsing github. I saw that there was Tune support at one point, along with a fork of `TrialRunner`. Is there anything on the Tune side that we can expose to make this easier?

**Comment by raubitsj** [comment]
@richardliaw 
Excellent!
We have been working on integrating Tune with wandb.  The support was removed from this branch temporarily as some of the underlying code was refactored.  I will restore the preliminary Tune support this week and would like to talk about integration possibilities.  In the last implementation there were a few API enhancements that would have made the integration cleaner.

**Comment by richardliaw** [comment]
Got it! Just cc me; more than glad to help.

**Comment by raubitsj** [comment]
@richardliaw 
We have added preliminary support for ray/tune support documented at:
https://docs.wandb.com/sweeps/ray-tune

Over the next few weeks we will be improving compatibility with ray/tune search and scheduler algorithms.

We would love to talk about ways we can contribute to ray/tune and possibly integrate some of our work in the future.

**Comment by richardliaw** [comment]
Awesome; thanks for the ping! I just sent a message out to [your first name] @ [your last name].org to kick off a conversation. Let me know if that's right.

**Pull request merged**
