### PR TITLE
Fix histogram logging for sparse tensors

### PR DESCRIPTION
**Pull request by adrnswanberg**

### CODE REVIEW

**Comment by adrnswanberg** [comment]
@raubitsj any idea what's up with this test failure?

`Traceback (most recent call last):
  File "/root/repo/venv/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/root/repo/venv/lib/python2.7/site-packages/pip/_internal/main.py", line 45, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/root/repo/venv/lib/python2.7/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/root/repo/venv/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 23, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/root/repo/venv/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 17, in <module>
    from pip._internal.index import PackageFinder
ImportError: cannot import name PackageFinder`

**Comment by vanpelt** [comment]
I fixed the pip issue in master yesterday.

**Comment by raubitsj** [comment]
Ooops. i thought this was synced with master already, I removed my hacks and rolled in your fixes.
@adrnswanberg , can you resolve the noml issue cvp raised

**Comment by adrnswanberg** [comment]
@vanpelt how do you suggest dealing with numpy not being available? try/catch the import?

**Comment by raubitsj** [comment]
Other examples in wandb_torch:
        numpy = util.get_module("numpy", "Could not import numpy")

**Comment by adrnswanberg** [comment]
> Other examples in wandb_torch:
> numpy = util.get_module("numpy", "Could not import numpy")

Maybe this is a dumb question but...that function raises an exception if numpy can't be imported right? Wouldn't that continue to fail the test in question?

**Comment by raubitsj** [comment]
The point is that you could do this on a machine without numpy:
```
import wandb
wandb.init()
wandb.log(dict(this=2))
```

With your change, numpy is required on a system even if they don't use torch with sparse tensors

**Comment by vanpelt** [comment]
@adrnswanberg you should skip the test in the noml environment

**Comment by adrnswanberg** [comment]
Ahhh ok I get it now. Sorry it's been a while!

**Comment by adrnswanberg** [comment]
> A couple comments and a request:
> comments:
> 
> * looks like the histogram will sometimes now have 65 bins instead of 64, any issue with the UI?
> * The histogram will also no longer be always linear in the key space, issue with the UI?
>   request:
> * add a small standalone test in "standalone_tests/" so we can make sure cuda tensors are also good

Done

**Pull request merged**
