### PR TITLE
Add debug function to dump all stacks

### PR DESCRIPTION
**Pull request by raubitsj**
Description
-----------

Allows you to print all threads stack traces in each process for debugging.

```

$ pip install --upgrade git+https://github.com/wandb/pyrasite.git
$ cat wandb/debug.log | grep "backend process with pid:"
2021-06-02 14:03:22,922 INFO    MainThread:1827997 [backend.py:ensure_launched():137] started backend process with pid: 1828067
$ pyrasite 1828067 debug/call-log-all-threads.py
# or
$ pyrasite-shell 1828067
# NOTE that on linux you will have to enable ptrace by some means, this is the easiest (but has widest implications for security):
# echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope
```

The above is a similar interface which pycharm provides: (but without the pycharm)
https://www.jetbrains.com/help/pycharm/attaching-to-local-process.html

Testing
-------

Manually tested on linux

### CODE REVIEW

**Comment by dannygoldstein** [comment]
hm, i'm unable to get this working on OSX, pyrasite-shell just hangs for me

**Comment by dannygoldstein** [comment]
hangs on 

```
^CTraceback (most recent call last):
  File "/Users/danielgoldstein/.pyenv/versions/wandb-3.8/bin/pyrasite-shell", line 8, in <module>
    sys.exit(shell())
  File "/Users/danielgoldstein/.pyenv/versions/3.8.2/envs/wandb-3.8/lib/python3.8/site-packages/pyrasite/tools/shell.py", line 30, in shell
    ipc.connect()
  File "/Users/danielgoldstein/.pyenv/versions/3.8.2/envs/wandb-3.8/lib/python3.8/site-packages/pyrasite/ipc.py", line 95, in connect
    self.wait()
  File "/Users/danielgoldstein/.pyenv/versions/3.8.2/envs/wandb-3.8/lib/python3.8/site-packages/pyrasite/ipc.py", line 151, in wait
    (clientsocket, address) = self.server_sock.accept()
  File "/Users/danielgoldstein/.pyenv/versions/3.8.2/lib/python3.8/socket.py", line 292, in accept
    fd, addr = self._accept()
```

**Comment by dannygoldstein** [comment]
hm, if i follow the advice here, 

https://github.com/lmacken/pyrasite/issues/60

I see 

`b'Unable to find Mach task port for process-id 47490: (os/kern) failure (0x5).\n (please check gdb is codesigned - see taskgated(8))\nNo symbol table is loaded.  Use the "file" command.\nNo symbol table is loaded.  Use the "file" command.\nNo symbol table is loaded.  Use the "file" command.\n'`

**Comment by dannygoldstein** [comment]
I followed this guide on OSX to codesign my copy of gdb:

https://gist.github.com/hlissner/898b7dfc0a3b63824a70e15cd0180154

but am still getting the same error as above

**Comment by raubitsj** [comment]
@dannygoldstein thanks for going through the steps, I hadnt tried with OSX, just linux.  i saw the codesigning madness but I didnt try to mess with it yet.  It would be nice to know what magic would allow it to work on OSX.   I am happy to dig in next time im hacking on a mac.

**Comment by raubitsj** [comment]
I made a new fork at:
https://github.com/wandb/pyrasite/
Which has some fixes cherrypicked from elsewhere and some of my own tweaks, so for now lets use:
```
pip install --upgrade git+https://github.com/wandb/pyrasite.git
```

**Pull request merged**
