### PR TITLE
[WB-5925] Fix sorting of importances

### PR DESCRIPTION
**Pull request by alexandrehsd**
https://wandb.atlassian.net/browse/WB-5925

This PR solves issue #2351 

https://github.com/wandb/client/issues/2351

Description
I sorted the `importances` in descending order. By doing so, the order of `importances` will match exactly the order of `feature_names` in the plot of feature importances.

What does the PR do?

It fixes the order of the feature names in the `plot_feature_importances` plot.

Testing
-------

How was this PR tested?
I ran all the tests of the library accordingly to what is explained in the CONTRIBUTING.md file. Besides, I reproduced the code containing the changes I did, and then the plot behaved as expected. 

Release Notes
Below, please enter user-facing release notes as one or more bullet points.
If your change is not user-visible, write NO RELEASE NOTES instead, with no bullet points.

------------- BEGIN RELEASE NOTES ------------------
Fixes a bug where feature importances were not correctly matched with feature names in sklearn plots 
------------- END RELEASE NOTES --------------------

### CODE REVIEW

**Review by dannygoldstein — APPROVED** [review]

**Review by dannygoldstein — CHANGES_REQUESTED** [review]
This seems to be causing some issues with our test suite, @alexandrehsd can you take a look?

**Comment by alexandrehsd** [comment]
Thank you very much for pointing that out @dannygoldstein. I'm sorry for replying late, I was involved in many side projects. In the next few days, I'm gonna try to fix whatever went wrong in the code checks.

**Comment by dannygoldstein** [comment]
I went ahead and fixed this since it was on my backlog. The problem was that for some of the models that we support for arguments to the plot_feature_importances function (anything with the `coef_` attribute), the feature importances array that is returned had shape `(n_classes, n_features)` instead of `(n_features,)`. This broke the assumption that a feature importance was a scalar. 

What I did was in those cases I calculated a per feature importance by taking the median of importances across all classes.

**Review by dannygoldstein — COMMENTED** [review]
unblocking this and requesting external review from @raubitsj  (since I made the changes in the end).

**Review by dannygoldstein — APPROVED** [review]

**Comment by dannygoldstein** [comment]
After a discussion with @kylegoyette I decided that the mean / median approach was not correct: in cases where the feature importances are two dimensional and represent coefficients of linear models, the taking the mean or median can give an incorrect result. Imagine a coefficient matrix like 

```
[[-1, 1], [1, -1]]
```

where each column represents a feature and each row represents a class. If we took the axis=0 median or mean of these coefficients, they would come out to zero importance which is definitely not correct - it seems like both features are important here for both classes.

I think what we have to do there is specify that we can only handle effectively 1d feature importance arrays. That is, anything where `np.prod(array.shape) == array.shape[0]`. 

I have updated the PR to warn if we encounter a feature importance array that does not satisfy this and return without raising an exception .

**Review by KyleGoyette — APPROVED** [review]

**Pull request merged**
