### PR TITLE
Replace deprecated threading aliases

### PR DESCRIPTION
**Pull request by hugovk**
Fixes WB-NNNN
Fixes #NNNN

Description
-----------
What does the PR do?

`threading.currentThread`, `getName`, `setDaemon` and `isSet` were deprecated in Python 3.10 (October 2021).

Replace with `threading.current_thread`, `name`, `daemon` and `is_set` added in Python 2.6 (October 2008).

* https://docs.python.org/3.12/whatsnew/3.10.html#deprecated
* https://github.com/python/cpython/pull/25174

Testing
-------
How was this PR tested?

Untested.

Checklist
-------
- Include reference to internal ticket "Fixes WB-NNNN" (and github issue "Fixes #NNNN" if applicable)
  - N/A

### CODE REVIEW

**Comment by kptkin** [comment]
Hi @hugovk thanks a lot of the fix!

**Comment by kptkin** [comment]
should we also fix the code that we vendor?

cc: @raubitsj

**Comment by hugovk** [comment]
Yes, I recommend either fixing tornado, or upgrading to v6: 
 https://github.com/tornadoweb/tornado/commit/68289914b7c2d4c1c09015c762ff4b02013f6df0

**Review by raubitsj — APPROVED** [review]
Thanks...
We will add a custom flake8 rule to avoid reintroducing deprecated interfaces like this

**Pull request merged**
