### PR TITLE
Rewrite local controller using wandb/sweeps

### PR DESCRIPTION
**Pull request by dannygoldstein**
This PR integrates wandb/sweeps with wandb/client. It reimplements the local controller using wandb/sweeps. This syncs the sweeps code between client and core. 

Summary of changes:

- Removes `client/wandb/sweeps` and replaces with `wandb/sweeps` as a submodule.
- Updates `setup.py` to read requirements from `wandb/sweeps/requirements.txt` and optionally install them using `pip install wandb[sweeps]`. 
- Does some refactoring of `wandb.sweep` and `wandb.controller` to avoid having to import dependencies of `wandb/sweeps` unless explicitly using the local controller
- Updates unit tests to reflect new sweeps engine wandb/sweeps
- Retires raytune sweeps, hyperopt, and envelope stopping. 

I did extensive manual testing of the local controller rewrite. It's hard to add unit tests for the local controller because of the complex interactions with the backend. I spoke to @raubitsj and we decided to punt  on extensively unittesting this until the new runqueue backend is implemented in gorilla for the local controller. 

------------- BEGIN RELEASE NOTES ------------------
Implements the sweep local controller using wandb/sweeps
------------- END RELEASE NOTES --------------------

### CODE REVIEW

**Review by vanpelt — COMMENTED** [review]
Looks good.  Not sure if this will effect local development.  I would verify the new 3rd party open source developer usecase and the internal CVP been developing on wandb for years usecase in terms of any additional steps required to get the submodule etc.

Another scenarios to think about are users installing directly from git.  There are times where we need users to install directly from git.  I tried this and it looks like it's properly adding the submodule but locally I'm still getting errors when trying to run `agent` or `sweep` commands after installing from your branch.

```
pip install --upgrade "git+git://github.com/dannygoldstein/client.git@local-controller#egg=wandb[sweeps]"
```

```
 wandb agent --help                                                                                       
Error importing optional module wandb.sweeps
Traceback (most recent call last):
  File "/Users/vanpelt/.pyenv/versions/3.7.5/envs/wandb-3.7/lib/python3.7/site-packages/wandb/util.py", line 185, in get_module
    return import_module(name)
  File "/Users/vanpelt/.pyenv/versions/3.7.5/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/vanpelt/.pyenv/versions/3.7.5/envs/wandb-3.7/lib/python3.7/site-packages/wandb/sweeps/__init__.py", line 1, in <module>
    from .run import next_run, stop_runs, SweepRun, RunState  # noqa
  File "/Users/vanpelt/.pyenv/versions/3.7.5/envs/wandb-3.7/lib/python3.7/site-packages/wandb/sweeps/run.py", line 7, in <module>
    from .config import SweepConfig
  File "/Users/vanpelt/.pyenv/versions/3.7.5/envs/wandb-3.7/lib/python3.7/site-packages/wandb/sweeps/config/__init__.py", line 3, in <module>
    from .cfg import SweepConfig, schema_violations_from_proposed_config
  File "/Users/vanpelt/.pyenv/versions/3.7.5/envs/wandb-3.7/lib/python3.7/site-packages/wandb/sweeps/config/cfg.py", line 9, in <module>
    from .schema import validator, fill_schema
  File "/Users/vanpelt/.pyenv/versions/3.7.5/envs/wandb-3.7/lib/python3.7/site-packages/wandb/sweeps/config/schema.py", line 11, in <module>
    with open(sweep_config_jsonschema_fname, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/vanpelt/.pyenv/versions/3.7.5/envs/wandb-3.7/lib/python3.7/site-packages/wandb/sweeps/config/schema.json'
Traceback (most recent call last):
  File "/Users/vanpelt/.pyenv/versions/wandb-3.7/bin/wandb", line 5, in <module>
    from wandb.cli.cli import cli
  File "/Users/vanpelt/.pyenv/versions/3.7.5/envs/wandb-3.7/lib/python3.7/site-packages/wandb/cli/cli.py", line 26, in <module>
    from wandb import Config, wandb_controller
  File "/Users/vanpelt/.pyenv/versions/3.7.5/envs/wandb-3.7/lib/python3.7/site-packages/wandb/wandb_controller.py", line 72, in <module>
    required="This module requires wandb to be built with the local "
  File "/Users/vanpelt/.pyenv/versions/3.7.5/envs/wandb-3.7/lib/python3.7/site-packages/wandb/util.py", line 192, in get_module
    raise wandb.Error(required)
wandb.errors.Error: This module requires wandb to be built with the local controller. Please run pip install wandb[sweeps]
```

It's fine if we error out the first time someone wants to run the local controller, but we definitely shouldn't require someone to run `pip install wandb[sweeps]` if they're just tring to run an agent or do something simple.

**Comment by dannygoldstein** [comment]
@vanpelt Thanks for presenting these thoughtful scenarios and for catching the CLI import issue. The issue you raised is now fixed. I neglected to refactor `cli.py` to use the module structure introduced in this PR so it was still looking for some things in old places, which triggered the imports of protected modules that you were seeing. After fixing this, I grepped for all uses of `controller` throughout the codebase and verified that the imports are now safe everywhere and that `wandb_controller` is only imported if the local controller is actually being used.

**Review by vanpelt — APPROVED** [review]
Looks great.  Only nit would be a callout in `CONTRIBUTORS.md` to tell users to run the needed submodule commands for this to work in either a new or existing dev setup.

**Comment by dannygoldstein** [comment]
> Looks great. Only nit would be a callout in `CONTRIBUTORS.md` to tell users to run the needed submodule commands for this to work in either a new or existing dev setup.

Done.

**Pull request merged**
