### PR TITLE
[CLI-471]: Fixed bug which creates extra `wandb` directory

### PR DESCRIPTION
**Pull request by tssweeney**
The root of the problem is that the "old" settings implementation uses a static method which uses a global variable to determine path. I decided to pass a `root_dir` override to the settings object (similar to the newer implementation), and successive calls to get and set to such directory.

Fixes: #1354
Reference: https://wandb.atlassian.net/browse/CLI-471

Changes:
    - `tests/wandb_integration_test.py`: added integration tests to ensure proper folder creation occurs
    - `wandb/apis/internal_runqueue.py` and `wandb/internal/internal_api/py`: the exact same change to pass root_dir to Settings initialization
    - `wandb/old/core.py`: added a root_dir parameter override to `wandb_dir()`
    - `wandb/old/settings.py`: added an attribute to the Settings class to contain the root_dir override and appropriately pass to subsequent calls.

### CODE REVIEW

**Review by vanpelt — APPROVED** [review]
Looks good, @raubitsj not sure if this would handle the case of reconfiguring later in the script.  Should be rare, and eventually we'll get rid of this old logic so I'm good 👍

**Comment by tssweeney** [comment]
Thanks Chris. @raubitsj since we specifically spoke about backwards compatibility with old api, would appreciate eyes/thoughts! Thanks!

**Comment by raubitsj** [comment]
> Thanks Chris. @raubitsj since we specifically spoke about backwards compatibility with old api, would appreciate eyes/thoughts! Thanks!

ill give thoughts in a bit.

**Review by raubitsj — APPROVED** [review]
Looks great.... i really want to get rid of this old/settings stuff so the integration tests will be very helpful.

**Pull request merged**
