### PR TITLE
[WB-4536] Get the version ID for your artifact at creation time, and immediately throw an error if upload fails

### PR DESCRIPTION
**Pull request by annirudh**
https://wandb.atlassian.net/browse/WB-4536

Description
-----------

If we have an internet connection, on `log_artifact` we now also build a lazy reference to that artifact. Calling any artifact methods will subsequently block until the artifact has been logged and then fetch the public artifact. For example:

```
artifact = ...
run.log_artifact(artifact)
artifact.wait() # This will block until the artifact is logged
artifact.version # Immediately returns the version (e.g.: "v0") of the artifact we just logged
```

This means that once we call `log_artifact`, we can treat the `Artifact` object exactly as if it were an artifact fetched from the public API.

Testing
-------

Modified the load test to include a `blocking` option. Currently running an extended loadtest to make sure everything works.

### CODE REVIEW

**Review by vanpelt — APPROVED** [review]
Sweet!

**Comment by tssweeney** [comment]
Hey Anni, i keep hitting an error on the first artifact created. Try a script such as:
```
art_name = "artifact_{}".format(time.time())
art_type = "type_{}".format(time.time())

run = wandb.init(project="dev_test")
art1 = wandb.Artifact(art_name,art_type)
art1.add_file("art_sync.py")
run.log_artifact(art1)
art1.wait()
```

to create a unique name/type for an artifact. This errors out:
```
  File "/Users/timothysweeney/workspace/wandb-client/wandb/apis/public.py", line 2544, in from_id
    [aliases[0]["artifactCollectionName"], aliases[0]["alias"]]
IndexError: list index out of range
```

This highlight a bug in the `from_id` method, but even after accounting for the index issue, we get something along the lines of:

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/timssweeney/dev_test/3ibhf0b0/artifact/1304188/wandb_manifest.json?Expires=1614199958&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JyJYDoqPb%2FNvXe0zK6ilj%2F%2BoZjptLvaWKzclA2bkEwAjhBiVyBkkNR%2BZaPT2M%2BOicjom84SXTBBKmrejNTQDrTi3iXXai5ZwXSziRDUAVyL0hOIxFhUK%2F%2BKB8dpuDPLDoLHxslPZTGcrh4LGH0rGuYELpeXf6GDsOcvpPoCAOH2y%2BFJg3zgM9JfTRJElG6fqQhv3WVEr%2BsWt%2FOO0FLqJcjjyfJ9wZuGQS5dFlK9RmeJ259cCGrwkhbKYKEN%2FtmhmQponoAaYdtcJ8YFU4kH6PJDmFdfr49APXqqUx4dZ1n92GNsCzLLyUN71SLKgIHD%2FXCFhkhT%2FQ0EElUxsiuVxJA%3D%3D
```

When fetching the manifest

**Comment by annirudh** [comment]
> Hey Anni, i keep hitting an error on the first artifact created. Try a script such as:
> 
> ```
> art_name = "artifact_{}".format(time.time())
> art_type = "type_{}".format(time.time())
> 
> run = wandb.init(project="dev_test")
> art1 = wandb.Artifact(art_name,art_type)
> art1.add_file("art_sync.py")
> run.log_artifact(art1)
> art1.wait()
> ```
> 
> to create a unique name/type for an artifact. This errors out:
> 
> ```
>   File "/Users/timothysweeney/workspace/wandb-client/wandb/apis/public.py", line 2544, in from_id
>     [aliases[0]["artifactCollectionName"], aliases[0]["alias"]]
> IndexError: list index out of range
> ```
> 
> This highlight a bug in the `from_id` method, but even after accounting for the index issue, we get something along the lines of:
> 
> ```
> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/wandb-production.appspot.com/timssweeney/dev_test/3ibhf0b0/artifact/1304188/wandb_manifest.json?Expires=1614199958&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=JyJYDoqPb%2FNvXe0zK6ilj%2F%2BoZjptLvaWKzclA2bkEwAjhBiVyBkkNR%2BZaPT2M%2BOicjom84SXTBBKmrejNTQDrTi3iXXai5ZwXSziRDUAVyL0hOIxFhUK%2F%2BKB8dpuDPLDoLHxslPZTGcrh4LGH0rGuYELpeXf6GDsOcvpPoCAOH2y%2BFJg3zgM9JfTRJElG6fqQhv3WVEr%2BsWt%2FOO0FLqJcjjyfJ9wZuGQS5dFlK9RmeJ259cCGrwkhbKYKEN%2FtmhmQponoAaYdtcJ8YFU4kH6PJDmFdfr49APXqqUx4dZ1n92GNsCzLLyUN71SLKgIHD%2FXCFhkhT%2FQ0EElUxsiuVxJA%3D%3D
> ```
> 
> When fetching the manifest

@tssweeney This should be fixed now!

**Comment by tssweeney** [comment]
Awesome! Thank you ... 🙏 . Also, can we add this to run.use_artifact as well (the case where you are "using" a newly created artifact?

**Comment by annirudh** [comment]
> Awesome! Thank you ... 🙏 . Also, can we add this to run.use_artifact as well (the case where you are "using" a newly created artifact?

Good call. Will do.

**Review by raubitsj — APPROVED** [review]
LGTM
async interface coming soon, but this looks great for now.

**Review by vanpelt — COMMENTED** [review]
Wow, lots of good stuff!

**Pull request merged**
