### PR TITLE
[WB-6076] escape filenames passed to publish_files, which expects globs

### PR DESCRIPTION
**Pull request by speezepearson**
Fixes WB-6076

Description
-----------

Escapes filenames that are passed into [InterfaceBase.publish_files](https://github.com/wandb/client/blob/e6445cdc6b032ba8b5df0807099b57a94780c84a/wandb/sdk/interface/interface.py#L348), which expects _globs_, not filenames, and therefore misbehaves when filenames contain `*` or `[...]`.

Testing
-------

Currently working on unit tests.

Manual testing: [repro](https://wandb.atlassian.net/browse/WB-6076?focusedCommentId=43246) before this change:
```bash
~/tempdir $ (cd ~/src/client/ && git checkout master)

~/tempdir $ python repro.py
<...wait a bit...>
^Z
[2]+  Stopped                 python repro.py

~/tempdir $ grep inoffensive_0 wandb/debug-internal.log
2022-01-28 12:21:22,517 INFO    SenderThread:85370 [sender.py:_save_file():944] saving file media/images/inoffensive_0_2f385627229499da4152.png with policy now
2022-01-28 12:21:22,903 INFO    Thread-13 :85370 [upload_job.py:push():137] Uploaded file /var/folders/wp/vvlmjhbd6q3gdr_l4grs6cyc0000gn/T/tmp1eis0p45wandb/jkbz5u30-media/images/inoffensive_0_2f385627229499da4152.png
2022-01-28 12:21:23,407 INFO    Thread-8  :85370 [dir_watcher.py:_on_file_created():217] file/dir created: /Users/pears/tempdir/wandb/run-20220128_122121-dwg2634u/files/media/images/inoffensive_0_2f385627229499da4152.png

~/tempdir $ grep 'weird chars' wandb/debug-internal.log
2022-01-28 12:21:22,519 INFO    SenderThread:85370 [sender.py:_save_file():944] saving file media/images/[weird chars]_1_54753c907b4065af6e3e.png with policy now
2022-01-28 12:21:23,406 INFO    Thread-8  :85370 [dir_watcher.py:_on_file_created():217] file/dir created: /Users/pears/tempdir/wandb/run-20220128_122121-dwg2634u/files/media/images/[weird chars]_1_54753c907b4065af6e3e.png
```
Note how the `Uploaded file` line is missing for the key with weird characters.

And after:
```bash
~/tempdir $ (cd ~/src/client/ && git checkout spencerpearson/brackets-escape)
Switched to branch 'spencerpearson/brackets-escape'
Your branch is up to date with 'origin/spencerpearson/brackets-escape'.

~/tempdir $ python repro.py
<...wait a bit...>
^Z
[2]+  Stopped                 python repro.py

~/tempdir $ grep inoffensive_0 wandb/debug-internal.log
2022-01-28 12:22:42,265 INFO    SenderThread:90789 [sender.py:_save_file():944] saving file media/images/inoffensive_0_a99039c325e43a8e4705.png with policy now
2022-01-28 12:22:42,660 INFO    Thread-13 :90789 [upload_job.py:push():137] Uploaded file /var/folders/wp/vvlmjhbd6q3gdr_l4grs6cyc0000gn/T/tmpjna_a9tswandb/19edoarb-media/images/inoffensive_0_a99039c325e43a8e4705.png
2022-01-28 12:22:43,156 INFO    Thread-8  :90789 [dir_watcher.py:_on_file_created():217] file/dir created: /Users/pears/tempdir/wandb/run-20220128_122241-1nzjog93/files/media/images/inoffensive_0_a99039c325e43a8e4705.png

~/tempdir $ grep 'weird chars' wandb/debug-internal.log
2022-01-28 12:22:42,266 INFO    SenderThread:90789 [sender.py:_save_file():944] saving file media/images/[[]weird chars]_1_1692ab4626d0418997ca.png with policy now
2022-01-28 12:22:42,661 INFO    Thread-14 :90789 [upload_job.py:push():137] Uploaded file /var/folders/wp/vvlmjhbd6q3gdr_l4grs6cyc0000gn/T/tmpjna_a9tswandb/3li9x4nz-media/images/[weird chars]_1_1692ab4626d0418997ca.png
2022-01-28 12:22:43,155 INFO    Thread-8  :90789 [dir_watcher.py:_on_file_created():217] file/dir created: /Users/pears/tempdir/wandb/run-20220128_122241-1nzjog93/files/media/images/[weird chars]_1_1692ab4626d0418997ca.png
```

### CODE REVIEW

**Comment by speezepearson** [comment]
Future potential changes:
- `publish_files` immediately converts its argument into a `pb.FilesRecord`. Is there any reason the callers shouldn't just construct the `FilesRecord` directly?
- The [`FilesItem`](https://github.com/wandb/client/blob/4b640ecbbc32ba7bbde5b5738e0dbf84190c5896/wandb/proto/wandb_internal.proto#L317) type has a field `string path`; but that value is treated ([access](https://github.com/wandb/client/blob/4b640ecbbc32ba7bbde5b5738e0dbf84190c5896/wandb/sdk/internal/sender.py#L952) -> [plumb](https://github.com/wandb/client/blob/4b640ecbbc32ba7bbde5b5738e0dbf84190c5896/wandb/sdk/internal/sender.py#L946) -> [use](https://github.com/wandb/client/blob/4b640ecbbc32ba7bbde5b5738e0dbf84190c5896/wandb/filesync/dir_watcher.py#L180)) as a glob, _not_ as a path. I'd like to rename this field to `glob`, or `path_glob`. Is there any reason this Protobuf field rename wouldn't be perfectly safe?

**Review by vanpelt — APPROVED** [review]
👍

**Comment by vanpelt** [comment]
Actually, we should really test this.  Probably belongs in `test_data_types.py`.

**Review by vanpelt — APPROVED** [review]
🔥

**Pull request merged**
