### PR TITLE
Fix WandbHook in tf2

### PR DESCRIPTION
**Pull request by adrnswanberg**
Use tf.estimator.SessionRunHook in tf>=1.14, and tf.train.SessionRunHook otherwise.

### CODE REVIEW

**Comment by adrnswanberg** [comment]
Feel free to merge yourself if this looks good.

**Comment by raubitsj** [comment]
In the CLI we tend to not rely on versions of packages and instead about the existence of interfaces.  Can you restructure the change that way?
Prefer the current interface and fallback to the old one.

**Comment by shawnlewis** [comment]
But we're not merging til Adrian fixes as Jeff said right?

**Comment by adrnswanberg** [comment]
Updated based on Jeff's comments. Tests seem fine except for edge-ml which is flaky as always. Merging.

**Pull request merged**
