### PR TITLE
[WB-3749,WB-3788,WB-3807] fix logging and login issues

### PR DESCRIPTION
**Pull request by raubitsj**
https://wandb.atlassian.net/browse/WB-3807
https://wandb.atlassian.net/browse/WB-3788
https://wandb.atlassian.net/browse/WB-3749

3807:
Disable debug-cli.log for now.  It was breaking all cli commands without a `wandb` directory, and a simple fix (commented out in this PR) to create the wandb directory would create too many wandb dirs

3788:
We were creating logger instances in modules that were not supposed to have them... Now we pass logger around,   There is another PR after release that makes this cleaner and adds type checks

3749:
We were doing login wrong in a bunch of places.   This change gets us closer to handling login in one place.   It also moves the viewer query to wandb_init rather than setup which is more sane right now.

Regression:
https://wandb.ai/jeffr/regression/groups/20201104-0.10.9.dev1-fix_login-logging-oh-my-39d6ef1-sg7moi

### CODE REVIEW

**Review by vanpelt — COMMENTED** [review]
Sorry about that, I thought it just used the system tmp directory if we didn't have a wandb dir, I guess I still need to make that dir...  I added this because we got a bunch of stacktraces in our cli commands because the default logger just writes to stdout.

**Comment by raubitsj** [comment]
@vanpelt , i couldnt reproduce that behavior (the spurious log output),  do you have an example of a CLI command that would cause that?

**Comment by vanpelt** [comment]
Yeah, set `WANDB_BASE_URL=http://localhost:98127` and run `wandb login`

**Comment by raubitsj** [comment]
@vanpelt , thanks, i had been so use to that spam i began to think it was normal.  :)
I will add back the debug-cli.log, i just want to do it a bit more narrow than for all cli commands to avoid the spurious wandb dirs.

**Pull request merged**
