### PR TITLE
feat(modelreg): KerasCallback model artifact saving -- sanitize artifact name

### PR DESCRIPTION
**Pull request by vwrj**
Description
-----------
Sanitizes artifact name. 

Testing
-------
How was this PR tested?

Checklist
-------
- Include reference to internal ticket "Fixes WB-NNNN" (and github issue "Fixes #NNNN" if applicable)

### CODE REVIEW

**Comment by raubitsj** [comment]
More a comment on https://github.com/wandb/client/pull/3909:
Are we comfortable with changing this default behavior... everyone who uses the wandb keras callback will get artifact models now.   I think if we are going to do this, we should at least have an opt-out, what do you think?
Do you have any data on success/failures from users who have opted in to this feature?

**Comment by raubitsj** [comment]
Also. it looks like the only way to use this feature is to trigger a deprecation:
```
wandb: WARNING The save_model argument by default saves the model in the HDF5 format that cannot save custom objects like subclassed models and custom layers. This behavior will be deprecated in a future release in favor of the SavedModel format. Meanwhile, the HDF5 model is saved as W&B files and the SavedModel as W&B Artifacts.
```
Seems strange to introduce a new feature behind a deprecation flag :)

**Comment by vwrj** [comment]
> More a comment on #3909: Are we comfortable with changing this default behavior... everyone who uses the wandb keras callback will get artifact models now. I think if we are going to do this, we should at least have an opt-out, what do you think? Do you have any data on success/failures from users who have opted in to this feature?

The opt-out would be setting the argument `save_model` to `False`. It currently defaults to True. Since the inception of this boolean, we've always defaulted to saving the best model as a `.h5` file. I've spoken to @ayulockin who recommends saving in the `tf` format, which is how we save it in the Artifact. 

I think ultimately, we want these integrations to save models as artifacts so that users can start using them in the Model Registry. 

Because `save_model` defaults to `True`, I'm not sure if we have much data from users who have opted out.

**Comment by raubitsj** [comment]
To be clear.. i am fine with this change to turn this on, but it could have more collateral damage.   Just want to make sure the risk was considered (and potentially better understood using data from usage) and the reward was greater.

**Comment by vwrj** [comment]
> To be clear.. i am fine with this change to turn this on, but it could have more collateral damage. Just want to make sure the risk was considered (and potentially better understood using data from usage) and the reward was greater.

Fair and reasonable. I think we're comfortable with the risk and fully prepared to jump onto any support issues that may arise from this.

**Review by raubitsj — APPROVED** [review]

**Review by kptkin — COMMENTED** [review]
Agreed with Jeff's comments

**Pull request merged**
