### PR TITLE
[CLI-133] Allow renaming groups of completed runs

### LINKED ISSUE #753: Allow renaming groups of completed runs
Is there any way to move a 'run' to another 'group' or changing the name of 'group'? I mistakenly set wrong group name for a run but couldn't find how to fix it!

### PR DESCRIPTION
**Pull request by ariG23498**
[CLI-133](https://wandb.atlassian.net/browse/CLI-133)

Description
Helps update the group of runs after the runs are complete.

The code to verify:

```python
api = wandb.Api()
runs = api.runs('<entity>/<project>')
runs[0].group = 'modified_group_name'
runs[0].update()
```
Fixes #753 

Testing
-------
`make test`

### CODE REVIEW

**Review by annirudh — APPROVED** [review]

**Comment by zhihanyang2022** [comment]
This sounds great; how exactly does this work? I don't see it in the documentation.

**Comment by magehrig** [comment]
Any updates on @zhihanyang2022 question? I don't seem to be able to rename groups, let alone move runs to different groups on the webpage

**Comment by busycalibrating** [comment]
But this feature doesn't seem to let me merge runs from one group to another, right?

**Comment by vanpelt** [comment]
@busycalibrating changing a runs group would merge it from it's existing group into a new one.  For example the following code would move a run from group1 to group2.

```
api = wandb.Api()
run = api.run("USERNAME/PROJECT/RUN_ID")
print(run.group) #=> group1
run.group = "group2"
run.save()
```

**Pull request merged**
