### PR TITLE
[do not merge] [debug-branch] Add init timeout as a setting

### PR DESCRIPTION
**Pull request by kptkin**
Description
-----------
What does the PR do?

Adds timeout as an environment variable. This will allow users with slower network to increase their timeout.

Testing
-------
How was this PR tested?

### CODE REVIEW

**Review by dmitryduev — APPROVED** [review]
LGTM! thanks @kptkin

**Comment by kptkin** [comment]
Once the timeout issue is resolved, please close this branch

**Comment by raubitsj** [comment]
marking as draft to make it less likely it gets merged.

**Comment by kptkin** [comment]
Informed the customer about the new release. I think we can close this one.

**Pull request closed without merging**
