### PR TITLE
Catboost: Plot Feature importances after model training (similar to sklearn)

### PR DESCRIPTION
**Pull request by neomatrix369**
On the back of related issues #992, https://github.com/wandb/client/issues/981 and #965, implementing check for `feature_importances_` attribute in `plot_feature_importance()` for both the regressor and classifier Catboost model types.

Just like `wandb.sklearn.plot_feature_importances()`, we can now call `wandb.catboost.plot_feature_importances()` for both `CatBoostRegressor` and `CatBoostClassifier` models.

I hope the CI/CD is able to test this out, as I wasn't able to run it using my own model setup. But plan to do that asap.

### CODE REVIEW

**Comment by neomatrix369** [comment]
Please do let me know if I need to do anything else in terms of setup or docs in order for this feature to become functional and acceptable.

**Comment by lukas** [comment]
Mani - this looks good to me. Thanks! Do you have a an example script or project I could use to try it out?

**Comment by neomatrix369** [comment]
> Mani - this looks good to me. Thanks! Do you have a an example script or project I could use to try it out?

I have written a couple of tests which kinda show how to use it, but I will be deploying it via my own project first and then I can share a bit of the code. That's my initial plan hence I tagged the PR to WIP.

I'll come back with a tangible catboost example for you. Thanks for the patience.

**Comment by neomatrix369** [comment]
> Mani - this looks good to me. Thanks! Do you have a an example script or project I could use to try it out?

Normally running the tests pushes a FI json to my own dashboard, for some reason, it didn't do it for the catboost test, not sure why. Do you have any comments on that?

I was able to see my scikitlearn test create a run in my dashboard but didn't see any for this one? What do you think might have happened?

**Comment by neomatrix369** [comment]
A very simple example would be this:

```python

from sklearn.datasets import make_regression
from catboost import CatBoostRegressor, CatBoostClassifier
import wandb

from wandb.catboost import plot_feature_importances

X, y = make_regression(n_features=2, random_state=42)
two_features = ['a', 'b']
model = CatBoostRegressor(random_state=42)
model = model.fit(X, y)

plot_feature_importances(model, feature_names=two_features)
```
You should get a bar-chart with two-features shown.  As per the docs, the number of features depends on how deep the trees are defined during initialisation of the class `CatBoostRegressor` or `CatBoostClassifier`.

**Comment by neomatrix369** [comment]
I have already run it via my model builder and I can see the bar graph in the dashboard.

**Comment by vanpelt** [comment]
@neomatrix369 this looks good.  The PR still says WIP, did you want to make any more changes or is it ready to merge?

**Comment by neomatrix369** [comment]
> @neomatrix369 this looks good. The PR still says WIP, did you want to make any more changes or is it ready to merge?

It's good to be merged now. No more changes required. I will be sharing a notebook with full implementation using `wandb` and `catboost` separately ;)

**Comment by neomatrix369** [comment]
> > @neomatrix369 this looks good. The PR still says WIP, did you want to make any more changes or is it ready to merge?
> 
> It's good to be merged now. No more changes required. I will be sharing a notebook with full implementation using `wandb` and `catboost` separately ;)

**CatBoost Feature Importances using W&B:** https://github.com/neomatrix369/awesome-ai-ml-dl/blob/master/examples/cloud-devops-infra/wandb/feature-importance/catboost_feature_importance_tutorial.ipynb

**Pull request merged**
