### PR TITLE
update sweeps engine to 5a434f3

### PR DESCRIPTION
**Pull request by dannygoldstein**
Description
-----------

Updates the sweeps engine to the latest version.

Summary of changes:

```
commit 5a434f32947d7fa106ffe5ef2fd65ca2d5808afd (HEAD -> updateSweeps, origin/master, origin/HEAD, master)
Author: Danny Goldstein <danny@goldstein.cloud>
Date:   Wed Aug 18 16:21:42 2021 -0700

    Revert "Revert "Vectorize sweeps so that it can be used as a target for NextNArgs in gorilla (#33)" (#37)" (#39)

    This reverts commit b0d1b4d3ab48a9c18e191910cb3c527008e60b00.

commit ca440367d7ed667b3f578b1c84759217be39dbdb
Author: Danny Goldstein <danny@goldstein.cloud>
Date:   Wed Aug 11 17:28:15 2021 -0700

    make error message  for "could not find value" more informative (#38)

commit 54fa10715de400d4fbfed0adafb0be913f1e504b
Author: Danny Goldstein <danny@goldstein.cloud>
Date:   Wed Aug 11 16:44:21 2021 -0700

    handle duplicated categorical values in grid search (#36)

commit b0d1b4d3ab48a9c18e191910cb3c527008e60b00
Author: Danny Goldstein <danny@goldstein.cloud>
Date:   Wed Aug 11 16:31:29 2021 -0700

    Revert "Vectorize sweeps so that it can be used as a target for NextNArgs in gorilla (#33)" (#37)

    This reverts commit ac9a11aa808591eb57d753235ebbb795c8d80d60.

commit ac9a11aa808591eb57d753235ebbb795c8d80d60
Author: Danny Goldstein <danny@goldstein.cloud>
Date:   Tue Aug 10 16:23:50 2021 -0700

    Vectorize sweeps so that it can be used as a target for NextNArgs in gorilla (#33)
```

Testing
-------

Tested in sweeps and using existing client unit tests for the local controller. 

Release Notes
-------------

Below, please enter user-facing release notes as one or more bullet points.
If your change is not user-visible, write `NO RELEASE NOTES` instead, with no bullet points.

------------- BEGIN RELEASE NOTES ------------------
Improves error handling in local controller sweeps engine 
------------- END RELEASE NOTES --------------------

### CODE REVIEW

**Review by raubitsj — APPROVED** [review]

**Comment by savvaki** [comment]
Good day, this change seems to have broken how sweeps work for me. I have used groups in order to sweep fixed sets of parameters. I now get this error:
 ``wandb: ERROR Error while calling W&B API: Invalid sweep config: unhashable type: 'dict' (<Response [400]>)``

My config:
```
program: src
method: grid
metric:
  goal: minimize
  name: val_loss
parameters:
  p:
    values:
      - outer_layers: 2
        inner_layers: 2
        inner_blocks: 2
      - outer_layers: 3
        inner_layers: 3
        inner_blocks: 3
      - outer_layers: 1
        inner_layers: 1
        inner_blocks: 3
```

**Comment by dannygoldstein** [comment]
Hi @savvaki, thanks for catching this. I'll push up a fix right now.

**Comment by dannygoldstein** [comment]
@savvaki This should be fixed now in production.

**Comment by savvaki** [comment]
@dannygoldstein Thank you. I appreciate the awesome support!

**Comment by dannygoldstein** [comment]
NP. Thanks for finding this bug

**Pull request merged**
