### PR TITLE
adds an option to specify different root dir for git using settings or environ variables

### PR DESCRIPTION
**Pull request by bcsherma**
Fixes WB-7454

Description
-----------
This PR introduces an environment variable, WANDB_GIT_ROOT, which can be used to specify a directory on the user's system which the git state will be captured from when tracking a run. Some users may be running experiments through a system like hydra which creates temporary directories where their code is run without the .git directory present. By setting WANDB_GIT_ROOT=<location-of-git-repository> these users can ensure that their git state is captured.

Testing
-------
[@bcsherma ] I've manually tested and verified that
1. Setting WANDB_GIT_ROOT=<location-of-git-repository> leads to the git info associated with runs being captured from the specified directory
2. Passing a non-existent directory or a directory that is not a repository triggers messages in the debug log and a term warning in the former case

[@kptkin] Added 2 test:
1. Integration test in `tests/unit_tests/wandb_run_test.py` to verify that the new argument is propagated to the server
2. Unit test to test the new exception case (when path is invalid) in `tests/unit_tests/test_git_repo.py`

### CODE REVIEW

**Review by vwrj — COMMENTED** [review]
Does code saving work in situations where GIT_ROOT != current working directory? i.e in your hydra use-case. Code saving (and patch saving) use GitRepo().root to fetch the directory that the code lives in.

**Comment by bcsherma** [comment]
> Does code saving work in situations where GIT_ROOT != current working directory? i.e in your hydra use-case. Code saving (and patch saving) use GitRepo().root to fetch the directory that the code lives in.

The patch is successfully saved from the WANDB_GIT_ROOT specified repo, but the code saved is just the script where wandb.init is called. And if you want to save all code you would just pass the root dir/glob that you want to save code from anyway https://docs.wandb.ai/ref/app/features/panels/code

**Comment by jovan-absci** [comment]
Hey guys, this is a really useful feature. Could you get this merged and released in the next version?

**Comment by kptkin** [comment]
> Hey guys, this is a really useful feature. Could you get this merged and released in the next version?

@jovan-absci We are planning to include this in the next release (planned to the beginning of Aug.)

**Review by vanpelt — COMMENTED** [review]
@KyleGoyette we likely want to make `launch` aware of this.  It's a bit different though...

@kptkin nevermind, read the description 🙃

**Review by raubitsj — APPROVED** [review]

**Pull request merged**
