### PR TITLE
Hyperband first run stops early

### PR DESCRIPTION
**Pull request by leopd**
Currently if you select "hyperband" (HB) early stopping criterion, the first run will go to completion.  This is really not what the HB algorithm is supposed to do.  The primary value of HB is that it explores lots of configurations at a very small fraction of the compute cost of a full run.  This allows it to find quite good configurations even without a surrogate model like in BayesOpt, but just using random candidates.  Importantly, it also finds decent configs extremely quickly - reliably getting to a decent value well before spending a full run's worth of compute budget if there are many bands.

Letting the first (randomly chosen) run go to completion destroys much of this value.  It adds a full 50% to the total compute budget for the sweep.  And it dramatically increases the sweep's latency before you see useful results.  With this change you might see good results after spending 0.25 runs' worth of compute, currently you have to wait until 1.25 runs' worth of compute - 5x longer.

The current behavior is much closer to the median stopping rule from [the Google Vizier paper (s3.2.2)](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/46180.pdf).

I recognize that some users might be relying on the current behavior as it might give better results when coupled with `grid` selection of candidates.  It is plausible that the ideal configuration is in a corner which would be the first run under grid.  In that case, this change would result in failing to find the ideal configuration well, although if the grid is not very coarse the structure should still show up.  If this case is considered important, the code is written such that an extra config flag could easily restore the original functionality.  (See comment on line 146 of `hyperband_stopping.py`.)

### CODE REVIEW

**Comment by charlesfrye** [comment]
Thanks for a really valuable and well-explained PR, @leopd!

My understanding of the hyperband algorithm and its benefits dovetails with his: it's designed to avoid running any max-budget runs until there's enough evidence that the configuration is near-optimal.

Given that, it's unclear to me that it should be allowed to be combined with grid search at all. In the words of the original paper, HB solves "a pure-exploration nonstochastic infinite-armed bandit problem", which is incompatible with grid search. Leo gave a nice example of how this can fail.

**Comment by leopd** [comment]
I agree that grid & hyperband aren't a very sensible combination.  Grid is well known in the HPO literature to be an extremely expensive way to find a good configuration.  However it can be quite useful in that the results of a grid sweep are very easy to interpret, readily making clear heatmaps and similar charts.  So I think the main correct use of grid is to understand the configuration space, and gain intuition about it.  As such, using an early stopping algorithm is a bit out of place: 1) it makes the results much harder to interpret, and clear results is IMHO the main reason to use grid search; 2) while it speeds up the sweep, if computational efficiency is a concern, you should not be using grid at all.

Relevant ref: [Bergstra, Bengio 2012](https://jmlr.csail.mit.edu/papers/volume13/bergstra12a/bergstra12a.pdf)

**Comment by leopd** [comment]
2de36d4 also fixes a probably rare race condition if a run were to report more than one metric before the controller runs.

**Comment by kptkin** [comment]
This PR seems to be correct from the theoretical point of view and would nice to have. 
However sweeps is now it's own repository so I'm closing it here.

@hu-po you might want to consider it for https://github.com/wandb/sweeps

**Pull request closed without merging**
