### PR TITLE
refactor unenumerated dependency on numpy

### PR DESCRIPTION
**Pull request by dannygoldstein**
Fixes https://github.com/wandb/client/issues/2187

### CODE REVIEW

**Comment by vanpelt** [comment]
We explicitly made numpy not a dependency of wandb.  If we do decide to add it as a dependency we need to refactor all of the places in the code that dynamically import wandb.

**Comment by dannygoldstein** [comment]
@vanpelt currently numpy is an unenumerated dependency of `wandb`. Installing the library from source via `pip install -e .` on a fresh python install `(apt-get update && apt-get install python3-pip), then  doing `import wandb; wandb.sweep({})`, gives 

```
>>> import wandb
>>> wandb.sweep({})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/client/wandb/wandb_controller.py", line 785, in sweep
    from wandb.sweeps.config import SweepConfig
  File "/client/wandb/sweeps/__init__.py", line 1, in <module>
    from wandb.sweeps.bayes_search import BayesianSearch
  File "/client/wandb/sweeps/bayes_search.py", line 12, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

which course of action would you recommend - adding numpy to `requirements.txt` or removing the codepath that hits `import numpy` from `wandb.sweep`? I went with the first option here but can try to implement the second instead.

**Comment by raubitsj** [comment]
If you want to add a variant for local controller which really requires numpy you can add it to setup.py:
```
    extras_require={
        'kubeflow': kubeflow_requirements,
        'gcp': gcp_requirements,
        'aws': aws_requirements,
        'grpc': grpc_requirements,
        'media': media_requirements
    }
```
Add a sweep_requirements maybe which would be the right thing to let people know they need specific requirements.

**Review by vanpelt — CHANGES_REQUESTED** [review]
This doesn't solve the problem.  We need to only import numpy when it's needed in sweeps and print an error message telling users to run `pip install wandb[sweeps]` to make the functionality that depends on it work.

**Review by vanpelt — APPROVED** [review]
Nice!  I *think `get_module` is performant and will use the already imported numpy if it's there instead of re-importing.  It's probably fine, but my only concern would be the actual sweep server we run attempting to reimport on every function call causing performance issues.

**Comment by dannygoldstein** [comment]
@vanpelt i verified that `importlib.import_module()` only reads a module off disk the first time it is called, then future calls hit a cache (so it should be performant as you say).

**Comment by vanpelt** [comment]
👍

**Pull request merged**
