### PR TITLE
[CLI-541] Made Collections Backwards Compatible to Avoid Deprecation Issues

### PR DESCRIPTION
**Pull request by tssweeney**
https://wandb.atlassian.net/browse/CLI-541

Running `PYTHONWARNINGS=default python -c "import wandb"` demonstrates that we have some deprecated module warnings (they are normally eaten up, but a savvy user found them). The biggest concern is with `collections` vs `collections.abc`. The abstract base classes (after py 3.3) have been moved to `collection.abc`. Each version of python basically says that this will break in the next version (they just keep moving the flag pole). Anyway, to get ahead of this, I build a compatibility module that acts as a pure passthrough in versions >=3.3, but for python versions before that, it patches in the `abc` module and its constituents. I then updated all the parts of the code which use a flavor of `collections.SOME_ABC` to be `wandb.compat.collections.abc.SOME_ABC`. This allow us to use the newer nomenclature, while still being backwards compat. So now we can do the following:

`import wandb.compat.collections` is exactly equivalent to `import collections` for versions >3.3. For versions before 3.3, it is a superset, in that `wandb.compat.collections` has an `abc` attribute (and module) which allows use of the 3.3+ syntax in <3.3 environments. all of the standard module import patterns are supported:
- `import wandb.compat.collections`
- `from wandb.compat.collections import *`
- `from wandb.compat.collections import MODULE/OBJ`
- `import wandb.compat.collections.abc`
- `from wandb.compat.collections.abc import *`
- `from wandb.compat.collections.abc import MODULE/OBJ`

Finally, I updated the code in `vendor` to use the compat module (which i think is less error prone than trying to upgrade the vendor package all together.

Fixes https://github.com/wandb/client/issues/1503

### CODE REVIEW

**Review by vanpelt — APPROVED** [review]
Fancy, I'm surprised the six library didn't have something for this...

**Comment by tssweeney** [comment]
> Fancy, I'm surprised the six library didn't have something for this...

Darn... yes, they do. That would have saved me some time today.

**Review by raubitsj — CHANGES_REQUESTED** [review]
I think we should use six instead of introducing our own.

**Review by vanpelt — APPROVED** [review]
SO CLEAN 😎

**Review by raubitsj — APPROVED** [review]
great

**Pull request merged**
