### PR TITLE
CLI: Don't start file-streaming until after UpsertBucket

### PR DESCRIPTION
**Pull request by adrianbg**
Fixes wandb/core#827 -- before we were starting file streaming right away and just letting the requests fail, causing all kinds of network traffic, and backend errors when we tried to upload files to nonexistant runs. Also do a lot of cleanup in the file-syncing code. Use more verbose variable names, and collect all the stuff related to file syncing together so we can hopefully split it out of the RunManager later.

### CODE REVIEW

**Comment by adrianbg** [comment]
Also removed the ugly locking stuff from streaming_log.py (because we don't need it any more), and switch the file events lock to a normal Python threading.Lock. We don't need an RWLock any more because all the file events stuff now only happens in one thread (the Watchdog Observer thread).

**Comment by shawnlewis** [comment]
Sick.

Can you test resuming (the various WANDB_RESUME modes), and check that:
- if you have no ~/.netrc and no wandb/settings it just prints a good error message and runs the run anyway
- after you do wandb login in this state, your run will always get saved (because we auto-generate entity and project names)

**Comment by adrianbg** [comment]
@shawnlewis still haven't done the testing you wanted but I fixed some bugs, replace shitty hacks with less shitty hacks, added comments...

**Comment by adrianbg** [comment]
Tested resuming and it seems like it doesn't work in the current master (d61157f7339d6210150dfff14f4de6bf81243f12) so I think I'm going to call this done for now

**Comment by adrianbg** [comment]
Chris raised an issue with ctrl-c'ing, which I've now fixed, along with a couple of other things I ran into. Going to merge this now.

**Pull request merged**
