### PR TITLE
changes to the docs

### PR DESCRIPTION
**Pull request by ariG23498**
This PR consists of the following changes:
1. Deletes the stale docs.
2. Updates the `generate.py`
3. Updates the `README.md` to help people generate the docs automatically.

### CODE REVIEW

**Comment by cvphelps** [comment]
@annirudh could you review and merge please

**Review by annirudh — APPROVED** [review]

**Comment by cvphelps** [comment]
@ariG23498 it looks like this needs to merge master, could you please pull that in and fix any conflicts, then merge in

**Comment by cvphelps** [comment]
Merged on behalf of Aritra because he doesn't have merge privileges

**Comment by annirudh** [comment]
Beautiful!

**Pull request merged**
