### PR TITLE
Add Preemptible Runs and Sweeps

### PR DESCRIPTION
**Pull request by dannygoldstein**
Description
-----------

This PR makes Sweeps and Runs preemptible, finishing #2122. The basic workflow is:

1. User process running in a scheduled environment learns it is about to be preempted by querying a metadata server, checking a queue, etc.
2. The user process in the CLI calls `run.mark_preempting()` (the only new user-facing interface exposed by this pr) which tells the _fs component of the CLI internal process to immediately send a message to the backend that the run believes that it is about to be preempted.
3. The fileStreamHandler on the backend receives the message from the CLI, and updates the state of the run to preempting.
4. If the run finishes with 0, it sends a message to the backend via the usual atexit hooks, setting the state of the run on the backend to finished.
5. If the run finishes with exit code != 0, then the backend assumes that the run crashed due to being preempted and marks the run preempted.
6. If the run stays in the preempting state for more than 5 minutes without a heartbeat, then the cron job that marks runs stale will mark the run preempted. In this case, it is assumed that the scheduler terminated the run in a manner consistent with pulling the plug on the machine: no reported exit code.

Testing
-------

I added 3 unit tests, one for each of the 3 test points that @raubitsj  shows in CONTRIBUTING.md.

### CODE REVIEW

**Review by vanpelt — APPROVED** [review]
Looks really clean, great tests, nice work!

**Review by raubitsj — APPROVED** [review]
nice.

you added:
run.mark_preempting()
but not:
wandb.mark_preempting()

which we have for other methods,  I think this is fine, since we probably should start getting away from these global methods, but it might make this feature a bit harder to use.

Instead of being able to do:
```
wandb.mark_preempting()
```

The caller would have to keep track of their run or do:
```
if wandb.run:
  wandb.run.mark_preempting()
```

**Review by vanpelt — APPROVED** [review]
Looks great, agreed with Jeff.  Let's add this to wandb/__init__.py along with the other `PreInitCallable` methods.

**Review by vanpelt — APPROVED** [review]
Nice!

**Pull request merged**
