### PR TITLE
[WB-8588] Add random element to debug-cli log file to prevent conflicts of multiple users

### PR DESCRIPTION
**Pull request by zythosec**
Fixes WB-8588

Description
-----------
- Uses mkstemp to generate a random filename with identifiable prefix/suffix for logging. This enables multiple clis to log on same machine by logging to different directories. 

Testing
-------
How was this PR tested? 

Checklist
-------
- Name PR "[WB-NNNN][WB-MMMM] Add support for..." similar to entries in CHANGELOG.md
- Include reference to internal ticket "Fixes WB-NNNN" (and github issue "Fixes #NNNN" if applicable)

### CODE REVIEW

**Review by raubitsj — COMMENTED** [review]
i think this is going to add too much noise in the wandb_dir. (it is bad enough with runs.. but every cli log will be too much noise i think)
maybe a directory where the randomized log goes.  and then if supported a symlink from the run dir named the original debug-cli.log...    This will clobber the previous symlink but all the logs will be in the wandb/cli-logs/ directory.

**Review by dmitryduev — COMMENTED** [review]
How about instead creating a user-specific log? E.g., get the current user, and append that? 
```python
import getpass
user = getpass.getuser()
```
Otherwise, I agree with @raubitsj, that will add too much noise.

**Comment by zythosec** [comment]
@raubitsj the issue with only having one file is that it prevents multiple users from running on the same machine at the same time. if they both try to wandb.login for instance, it will fail out. Looking deeper into it, it looks like there may still be additional pieces that would prevent two users from being able to run at the same time anyway.

@dmitryduev I wonder if all logs should be scoped and permissioned to the user that is running? 

Also another question for both of you, is there anything else that may prevent two users from running at the same time?

**Comment by raubitsj** [comment]
> @raubitsj the issue with only having one file is that it prevents multiple users from running on the same machine at the same time. if they both try to wandb.login for instance, it will fail out. Looking deeper into it, it looks like there may still be additional pieces that would prevent two users from being able to run at the same time anyway.


I was suggesting multiple files. But a symlink to the most recent one. We do this for our other logs. It should be safe

**Comment by vanpelt** [comment]
@manuel-delverme you can set the `TMPDIR` environment variable to a unique directory that's writable by you as a quick and dirty workaround, i.e.

```shell
mkdir /tmp/$(whoami)
export TMPDIR=/tmp/$(whoami)
```

**Comment by dmitryduev** [comment]
I scoped the cli-debug log to the user - does it look good? @vanpelt @zythosec @raubitsj

**Comment by zythosec** [comment]
Thanks @dmitryduev looks good to me. I can't approve my own PR, but approve the changes.

**Review by raubitsj — APPROVED** [review]

**Pull request merged**
