### PR TITLE
Fix BlockingIOError for centOS Linux distributions when saving larger files

### PR DESCRIPTION
**Pull request by konstantinjdobler**
https://github.com/wandb/client/issues/2182

Description
-----------
According to this ticket in the python issue tracker (https://bugs.python.org/issue43743), on some linux distributions `shutil`'s  `_fastcopy_sendfile` method can produce errors for larger files. The recommended fix is to fallback on another method by doing `shutil._USE_CP_SENDFILE = False`.

Testing
-------
I had this problem on centOS and can confirm this fixes the problem. I also tested on a OSX MacBook and the introduced change did not result in errors.

I am not sure if I added the distro package to the right requirements file.

@raubitsj @adrnswanberg tagged for review (I can't add them trough GitHub)

### CODE REVIEW

**Comment by konstantinjdobler** [comment]
The error is an import error because of the introduced `distro` dependency. Unfortunately I don't really know the project structure that well, so before I spam the CI server with a bunch of trial-and-errors, someone who actually knows  can tell me where it needs to go 😄

**Comment by vanpelt** [comment]
@konstantinjdobler thanks for this PR and sorry for the delayed response.  Unfortunately we generally avoid adding additional third party dependencies whenever possible and adding `distro` for this specific case is a non-starter.  I *think we could do this with the standard libs `platform` module with `"centos" in platform.platform()`.

Are you sure this is true for all versions of centos?  Are there other linux distros / configurations this would be true for? For your specific usecase, I think you could just import shutil and set the global flag in your code before making `wandb` calls.

**Comment by vanpelt** [comment]
@konstantinjdobler I made a more generic [PR here](https://github.com/wandb/client/pull/2214).  We should get this out in the next release.

**Comment by konstantinjdobler** [comment]
Hey, thanks! When looking for the fix, I think using ` platform.platform()`was deprecated - they moved it into a regular PyPi package because it could be updated more frequently than the standard lib. Unfortunately importing `shutil` and setting the flag did not work in my case - I assume the flag needs to be set in the context of where `shutil` is actually used. But indeed I do not know if this error occurs in all versions of centos. Therefore, your version is better anyways  - thanks for the fix!

**Pull request closed without merging**
