### PR TITLE
Fix for Python 3.8 new locals() behavior.

### PR DESCRIPTION
**Pull request by madlag**
Looks like some debugger are doing some black magic stuff with locals() .
(I though at first it was Python 3.8.5 that introduced the bug, but it turned out it's something else).

The simple code 
```
def fun():
    k = locals()
    return "k" in k
```

Returns 'True' in this setup (Pycharm / pydev issue ???).
Still investing why, so you may wait before considering this PR.

### CODE REVIEW

**Comment by raubitsj** [comment]
@madlag Thanks for this PR, until you sent this I didnt realize that locals() behavior was not fully specified (looks like python 3.10 is fixing some of this)

Some of our sdk is generated code to preserve non type annotated python2 interfaces which is why this PR is failing in our CI

In order to generate those files you can run:
```
make test
```
or
```
tox -e codemod
```

**Comment by madlag** [comment]
OK, will run this.
I will actually modify it to a simpler dict(locals()) after reading the following:
https://nedbatchelder.com/blog/201211/tricky_locals.html

There should be a trace function registered somewhere (in pydev I suppose) that mess with locals, and explain the bug in this special case. I was getting mad because it was running OK in a terminal, and not in the IDE ! ;-)

**Comment by madlag** [comment]
I replaced the initial version with the "dict(locals()) version, run the python2.7 code generator and squashed the last commits.

**Review by raubitsj — APPROVED** [review]
LGTM, Thanks again... This is some good sleuthing to figure this one out.

**Pull request merged**
