### PR TITLE
(Recreated) The beginning of data sets

### PR DESCRIPTION
**Pull request by adrianbg**
The beginning of data sets: allow WBValue's to be stored in DataFrame's. Distinguish plain WBValue's, which can be serialized to JSON on their own, from Media objects, which need to be bound to a particular Run before they can be serialized. In either case, the resulting JSON structures should let us share data across Runs.

Since the original version of this pull request, I've removed the run ID's etc. stored in media -- we just assume they're original from the "current" run, whatever that is -- and restored the old behaviour of uploading sets of images as a JPEG of thumbnails without duplicating them as PNGs. Single images created as raw pixels will be stored as PNGs but not JPEGs.

### CODE REVIEW

**Comment by shawnlewis** [comment]
Yeah I'd like to sit down and go through this tomorrow (Thursday)

I'm trying to run the all_media_types.py standalone test, but having trouble getting all the dependencies installed.

I think it'd also be fantastic to test what happens when you don't have certain deps (the ones that we don't require but print warnings for when you try to use a specific feature). We can add this to Jeff's integration suite at some point, in the mean time we can run through it manually.

**Comment by vanpelt** [comment]
I can fix the edgeml test.

**Comment by vanpelt** [comment]
I'm still a little concerned that users which log an individual image using `wandb.log` will consume ~2x disk space with this release.  We might want to consider always just making a sprite for wandb.data_types logged with `wandb.log`.  I changed the tensorboard logger to always log a list of images even when there's only one.

**Comment by adrianbg** [comment]
We got rid of double-logging images.

I think pngs are gonna be a fact of life for logging datasets. Lossless compression is important for that case.

Turning images into lists for Tensorboard seems like a good idea. Thanks.

**Comment by vanpelt** [comment]
Tests are passing, I'm good to merge and release tomorrow.  @raubitsj can you run the integration suite?

**Comment by vanpelt** [comment]
@adrianbg I saw a ~50% size increase between my wandb sync on tensorboard with single image vs array of one image so I assumed we were double logging.  If the effect is just png vs jpg I'm fine taking that hit for lossless on a single image with wandb.log.

**Comment by raubitsj** [comment]
Regression running: (all 26 tests should pass)
https://app.wandb.ai/jeffr/regression/groups/20190524-0.8.1-feature_data-frame-media-33cd040-67f8uf

**Comment by shawnlewis** [comment]
Thanks Jeff!

@adrianbg Can you confirm we're not double-logging in the tensorboard case? I think once that's done, we're good to merge.

**Comment by raubitsj** [comment]
Here is the regression kicked off for the 0.8.1 release (for reference):
https://app.wandb.ai/jeffr/regression/groups/20190524-0.8.1-release-unknown-y8y9fo
(command line: `./regression.py --cli_release 0.8.1 --spec ::~broken .`)

**Comment by adrianbg** [comment]
Yeah, it'll either do a JPEG for an array of wandb.Images or a PNG for an
individual one. Either way there's no double logging.

**Pull request merged**
