### PR TITLE
Feature/parallelcoords

### PR DESCRIPTION
**Pull request by avionbg**
- Refactored the code, updated all variables to const / let (if they are reassigned later then we are using let), converted anonymous functions to arrow functions, updated import curly bracket spacing to the format in wandb, converted double quotation marks to single  etc.
- Updated logic for the parallel coordinates, removed brushend event (it seems its not needed), removed setState from parent react component (data sorting is persisted inside d3 now)
- Extracted hover lines to private function that is reused in drag-end event

### CODE REVIEW

**Comment by vanpelt** [comment]
@avionbg This looks great!  Excellent work.  @shawnlewis, it looks like the brushes are filtering on the chart, but they're not being applied to the global filters.  Can you point @avionbg in the right direction?  It also looks like the new logic for supplying dimensions isn't giving me configs in `wandb/big-history-test/runs` for instance, not sure if that's a separate bug or a part of this.

**Comment by shawnlewis** [comment]
Sure, look for this code:
```python
          onBrushEvent={(axis, low, high) => {
            this.props.batchActions([
              addFilter('select', filterKeyFromString(axis), '>', low),
              addFilter('select', filterKeyFromString(axis), '<', high),
            ]);
          }}
```
In https://github.com/wandb/client/blob/master/wandb/board/ui/src/components/PanelParallelCoord.js

That will set the selections in redux. You also need to populate the brushes from redux, like the code in that file does.

It looks like this behavior is actually broken in our currently released version.

**Comment by shawnlewis** [comment]
Not sure how to make es lint match. I just do "npm install -g eslint". You need to have .eslintrc in your the directory you're running your editor from. It's in the root directory of wandb/core

**Comment by shawnlewis** [comment]
Actually the redux selection behavior works fine in the currently version. We were missing the css so the plot looked all black. But I just pushed a fix.

To test:
  - create a project with a handful of runs (say ~10)
  - make a parallel coordinates plot with a few axes
  - Also make a "Run History Line Plot".
  - By default the Run History Line Plot will show data for the most recent 10 runs
  - Brush over an axis on the parallel coordinates plot. This should create a selection which you can see if you open the "1 Filters / 3 Selections" dropdown
  - The lines on Run History Line Plot should change to match the most recent ones from your selection

**Pull request merged**
