### PR TITLE
Fix code saving in notebooks by refreshing user settings after login

### PR DESCRIPTION
**Pull request by adrnswanberg**
This PR:

* Calls a function to refresh user settings after a login. This allows us to pull in code saving preferences, which fixes an existing issue with history not getting saved in notebooks.
* Refactors some viewer query logic in wandb_setup.

### CODE REVIEW

**Comment by raubitsj** [comment]
@adrnswanberg , is there a ticket associated with this PR?

**Review by vanpelt — APPROVED** [review]

**Comment by adrnswanberg** [comment]
@raubitsj no ticket that I could find, just something that I noticed while messing with jupyter.

**Comment by raubitsj** [comment]
> @raubitsj no ticket that I could find, just something that I noticed while messing with jupyter.

@adrnswanberg great. i noticed it also, i just didnt want to mess with that code right now.  THanks!

Im capturing the commented out code that you removed so it can be used as reference in the kaggle internet bug:
https://wandb.atlassian.net/browse/WB-3289

**Review by raubitsj — APPROVED** [review]
Looks like you might need to do some merge conflict, i think it is from your other PR

**Pull request merged**
