### PR TITLE
Don't allow unbounded paging in public API calls.

### PR DESCRIPTION
**Pull request by shawnlewis**

### CODE REVIEW

**Comment by shawnlewis** [comment]
I don't think so. per_page = None means use the default

**Comment by vanpelt** [comment]
Won’t we get an attribute error now since you don’t set pee_page?

**Comment by shawnlewis** [comment]
Oops, yup that was bone-headed. Just pushed a fix. Thanks

**Comment by vanpelt** [comment]
Looks good

**Pull request merged**
