### PR TITLE
Yaml doc string

### PR DESCRIPTION
**Pull request by ariG23498**
The following are the proposed changes:
1. A directory named `Mydocstring` has been added. The directory has the `extract` and the `parse` scripts used for to parse the docstring.
2. In the base folder, three new files are added namely `doc_gen_yaml.py`, `doc_structure.yaml` and `template.txt`.

Usage of the files:
```bash
$ python doc_gen_yaml.py doc_structure.yaml
```

To know more about the structure of the `yaml` here is a [notion doc](https://www.notion.so/Documentation-Generator-f59c57d6ea0443d3b79cf5bbd257dab1#2efce658641b480eaddaae60823d4461).

### CODE REVIEW

**Review by vanpelt — CHANGES_REQUESTED** [review]
I'm not a fan of this approach.  It looks extremely brittle.  Why can't we use `pydoc-markdown` and extend it?

Also there are no other directories with capital letters in this repository, and a directory named `Mydocstring` makes no sense.  

@cvphelps this is headed back towards the state we were in with the previous repo.  I really want to avoid a bunch of custom code that is difficult to maintain and bug prone.

**Comment by ariG23498** [comment]
Hey Chirs!
Thank you for your review. I would like to put your attention to the following aspects.
1. The popular tools that are used for documentation all use regex. pydoc-markdown uses regex too as can be seen [here](https://github.com/NiklasRosenstein/pydoc-markdown/blob/develop/pydoc-markdown/src/pydoc_markdown/contrib/processors/google.py).
2. Extending pydoc-markdown or sphinx would mean the same thing. We are required to customise the regex to extract the sections of docstring will be required by us.
3. The code that I have used has been taken from the [mydocstring repository](https://github.com/ooreilly/mydocstring). I did not want to use the `pypi package` as that did not have a particular regex expression that extracted docstring from class functions. This is the reason why I have used the extract.py and parse.py code files as it is and have made my own changes which works pretty well for the google stylised docstring.
4. My approach for documentation is to first extract the AST of the source code so that I can know the line numbers of the code in the repository. Then to parse the docstring with some basic regex and then using the extracted values of the docstring into the template text file.
5. Having a custom package would help us in the longer run as it not only gives us a flexible template but also reduces the dependancy issues.

**Comment by vanpelt** [comment]
> Hey Chris!
> Thank you for your review. I would like to put your attention to the following aspects.
> 
> 1. The popular tools that are used for documentation all use regex. pydoc-markdown uses regex too as can be seen [here](https://github.com/NiklasRosenstein/pydoc-markdown/blob/develop/pydoc-markdown/src/pydoc_markdown/contrib/processors/google.py).

Exactly, we can use their tested approach to parsing docs which is far less error prone than rolling our own from scratch.

> 2. Extending pydoc-markdown or sphinx would mean the same thing. We are required to customise the regex to extract the sections of docstring will be required by us.

We can extend their parsing and only write custom regex for the aspects of the docstrings we explictly extend / change.

> 3. The code that I have used has been taken from the [mydocstring repository](https://github.com/ooreilly/mydocstring). I did not want to use the `pypi package` as that did not have a particular regex expression that extracted docstring from class functions. This is the reason why I have used the extract.py and parse.py code files as it is and have made my own changes which works pretty well for the google stylised docstring.

"works pretty well" is what I'm worried about, what happens when it doesn't work?

> 4. My approach for documentation is to first extract the AST of the source code so that I can know the line numbers of the code in the repository. Then to parse the docstring with some basic regex and then using the extracted values of the docstring into the template text file.

Yes, this is exactly the same approach as pydoc-markdown

> 5. Having a custom package would help us in the longer run as it not only gives us a flexible template but also reduces the dependancy issues.

Having a completely custom package means only you know how it works and adds a big ongoing maintenance cost.  I'm not aware of any "dependancy issues".  pydoc-markdown would only be a dependency for developers and there should be no issues making it a dependency.

Regardless of the approach we use, the current code quality / layout is very poor and inconsistent the rest of this repository.  Adding a new directory named `Mydocstring` makes no sense at all.  If we do write our own code it should be well tested, documented and laid out in a consistent manner with the rest of the code base.

**Comment by ariG23498** [comment]
@vanpelt @cvphelps would you want to close this PR?
I do not think this is the way we would want to go any further.

**Pull request closed without merging**
