### PR TITLE
Fix sweep test to allow delay to test hyperband against qa or prod

### PR DESCRIPTION
**Pull request by raubitsj**
This takes a while to run but it will generate a nice project with stopped runs:
```
./sweep_check.py -t grid_hyper --grid_hyper_delay 30
```

### CODE REVIEW

**Comment by charlesfrye** [comment]
Do you have a completed project I can look at? Not sure what your u/n on wandb.ai is.

**Comment by raubitsj** [comment]
> Do you have a completed project I can look at? Not sure what your u/n on wandb.ai is.
> 
> I still see `stopped, saw: 0, expecting 3` when i run it. was this supposed to fix the test?

The test works and checks what it can, but the public api is no longer returning "stopped" flag so we can test it.

This fix just adds a delay that allows us to run an automated hyperband sweep against a live gorilla server without modifying the test.

**Comment by charlesfrye** [comment]
Gotcha, I misunderstood scope.

**Review by charlesfrye — APPROVED** [review]
lgtm

**Pull request merged**
